events {}

http {
    upstream go_backend {
        server 127.0.0.1:8080;
    }

    server {
        listen 8888 ssl;

        ssl_certificate     /deploy/certs/nginx.crt;
        ssl_certificate_key /deploy/certs/nginx.key;

        location /api/v1/ {
            proxy_pass http://go_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        location / {
            proxy_pass http://go_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
